blank_issues_enabled: false
contact_links:
  - name: Descargar la última versión
    url: https://github.com/danysers/ShiftNova/releases/latest
    about: Comprueba si el problema ya fue corregido en una versión reciente.
